<?php

    // Get the form fields, removing html tags and whitespace.
    $name = strip_tags(trim($_POST['name']));
    $name = str_replace(array('\r','\n'),array(' ',' '),$name);
    $email = filter_var(trim($_POST['email']), FILTER_SANITIZE_EMAIL);
    $referral = $_POST['find-us'];
    $message = strip_tags(trim($_POST['message']));
    $passphrase = strip_tags(trim($_POST['passphrase']));
    $isCheckedFollowup = (isset($_POST['followup']));

    // Check the data. If bad data, then reload the page with the error code set.
    if (empty($name) OR empty($message) OR !filter_var($email, FILTER_VALIDATE_EMAIL) OR ($passphrase != 'NITNA')) {
        header("Location: https://www.philipantin.com/index.php?success=-1#contact");
        exit;
    }

    // Set the email address to receive the email generated by the form.
    $recipient = 'webmaster@philipantin.com';

    // Set the email subject.
    $subject = "New contact from $name";

    // Build the email content.
    $email_content = "Name: $name\n";
    $email_content .= "Email: $email\n\n";
    $email_content .= "Referral: $referral\n\n";
    $email_content .= "Message:\n$message\n\n";
    if ($isCheckedFollowup) {
        $email_content .= "FOLLOWUP REQUESTED\n";
    }

    // Build the email headers.
    $email_headers = "From: $name <$email>";

    // Send the email.
    mail($recipient, $subject, $email_content, $email_headers);
    
    // Redirect to the index.html page with success code
    header("Location: https://www.philipantin.com/index.php?success=1#contact");
?>